### ISSUE TITLE
Pourquoi ça marche pas ... ????

### ISSUE THREAD

**Issue by 6be709c0** [AifeDesPaix/HotelDeluXxX#11]
En vrai, j'ai pas testé,
c'est juste histoire de dire bonjour.

Bonjour !

**Comment by aifedespaix** [comment]
cool ba ça marche alors, bonjour à toi

**Comment by aifedespaix** [comment]
gros manque de professionnalisme de ta part. DANGER /!\

**Comment by 6be709c0** [comment]
Ah oui, bien vue.
Merci beaucoup !

**Comment by aifedespaix** [comment]
f o la léssé ouvérte kar ya pu ri1 ki march

**Comment by 6be709c0** [comment]
J'ai pas trouvé sur Google Maps ou se trouve votre hôtel.
Pouvez vous me donnez un lien.
Merci

**Comment by aifedespaix** [comment]
6 rue des épagneul breton 64000 cool

**Comment by 6be709c0** [comment]
Introuvable : 
https://i.gyazo.com/b030bbf3906215d2e1904c176677819e.png

**Comment by aifedespaix** [comment]
Ok c'ets mergé sur master, merci pour ta contribution, à tchao bonsoire
